# Generated by Django 4.1.2 on 2023-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_customer_alter_book_title_alter_order_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
