# Generated by Django 4.1.5 on 2023-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='ordered_books', to='app.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
